name: 'ServiceNow DevOps Notification'
description: 'Send Job Notification to ServiceNow Devops'
inputs:
  devops-integration-user-name:
    description: 'Devops Integration User Name'
    required: true
  devops-integration-user-pass:
    description: 'Devops Integration User Pass'
    required: true
  instance-name: 
    description: 'ServiceNow Instance Name (e.g.: rapdevio)'
    required: true
  state:
    description: 'Orchestration Task State'
    required: true
  tool-id:
    description: 'Orchestration tool id'
    required: true
  context-github:
    description: 'Github context'
    required: true
  commits:
    description: 'List of commits that triggered the run'
    required: false
  upstream-task-url:
    description: 'upstream task that triggered execution'
    required: false
outputs:
    task-execution-url:
      description: 'task execution url'
branding:
  icon: 'arrow-right-circle'
  color: 'blue'
runs: 
  using: 'node12'
  main: 'dist/index.js'
