name: test-notification

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

env:
  commits: '[{"commitId": "${{ github.sha }}" }]'

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: send servicenow notification
        uses: ./
        with:
          instance-name: ${{ secrets.INSTANCE_NAME }}
          devops-integration-user-name: ${{ secrets.DEVOPS_INTEGRATION_USER_NAME }}
          devops-integration-user-pass: ${{ secrets.DEVOPS_INTEGRATION_USER_PASS }}
          tool-id: ${{ secrets.TOOL_ID}}
          context-github: ${{ toJSON(github) }}
          state: 'building'
          commits: ${{ env.commits }}
